### ISSUE TITLE
Serving cache in development

### ISSUE THREAD

**Issue by marconi** [andreyfedoseev/django-coffeescript#10]
If it caches to a path relative to STATIC_ROOT then how am I suppose to serve it in development since STATICFILES_DIRS can't have STATIC_ROOT in it?

**Comment by andreyfedoseev** [comment]
This is fixed in the latest version (0.7), I've just uploaded it to PyPi.

Add `'coffeescript.finders.CoffeescriptFinder'` to `STATICFILES_FINDERS`
