### ISSUE TITLE
subprocess.popen on windows

### ISSUE THREAD

**Issue by davideickhoff** [andreyfedoseev/django-coffeescript#12]
I know, we shouldn't use windows ;) 

However, windows users get an access denied error when calling the coffee executable.

This function call (in the templatetag):
        p = subprocess.Popen(args, stdin=subprocess.PIPE,
                             stdout=subprocess.PIPE, stderr=subprocess.PIPE)

need to have an additional shell=True keyword argument..

**Comment by andreyfedoseev** [comment]
This package is not longer maintained. 

Please use [django-static-precompiler](https://github.com/andreyfedoseev/django-static-precompiler)
