### ISSUE TITLE
 'coffeescript' is not a valid tag library

### ISSUE THREAD

**Issue by piousbox** [andreyfedoseev/django-coffeescript#13]
TemplateSyntaxError at /startups/

'coffeescript' is not a valid tag library: Template library coffeescript not found, tried django.templatetags.coffeescript,django.contrib.admin.templatetags.coffeescript,django.contrib.staticfiles.templatetags.coffeescript,django_extensions.templatetags.coffeescript

Request Method:     GET
Request URL:    http://localhost:8000/startups/
Django Version:     1.6
Exception Type:     TemplateSyntaxError
Exception Value:    

'coffeescript' is not a valid tag library: Template library coffeescript not found, tried django.templatetags.coffeescript,django.contrib.admin.templatetags.coffeescript,django.contrib.staticfiles.templatetags.coffeescript,django_extensions.templatetags.coffeescript

Exception Location:     /usr/local/lib/python2.6/dist-packages/django/template/defaulttags.py in load, line 1084
Python Executable:  /usr/bin/python
Python Version:     2.6.5
Python Path:    

['/home/piousbox/projects/startups',
 '/usr/local/lib/python2.6/dist-packages/distribute-0.7.3-py2.6.egg',
 '/usr/local/lib/python2.6/dist-packages/setuptools-1.3.2-py2.6.egg',
 '/usr/lib/python2.6',
 '/usr/lib/python2.6/plat-linux2',
 '/usr/lib/python2.6/lib-tk',
 '/usr/lib/python2.6/lib-old',
 '/usr/lib/python2.6/lib-dynload',
 '/usr/lib/python2.6/dist-packages',
 '/usr/lib/python2.6/dist-packages/PIL',
 '/usr/lib/python2.6/dist-packages/gst-0.10',
 '/usr/lib/pymodules/python2.6',
 '/usr/lib/python2.6/dist-packages/gtk-2.0',
 '/usr/lib/pymodules/python2.6/gtk-2.0',
 '/usr/local/lib/python2.6/dist-packages']

Server time:    Sun, 15 Dec 2013 20:01:02 +0000
Error during template rendering

In template /home/piousbox/projects/startups/templates/layouts/base.html, error at line 1
'coffeescript' is not a valid tag library: Template library coffeescript not found, tried django.templatetags.coffeescript,django.contrib.admin.templatetags.coffeescript,django.contrib.staticfiles.templatetags.coffeescript,django_extensions.templatetags.coffeescript
1   {% load coffeescript %}
2  
3  
4   <!DOCTYPE html>
5   <html lang='en'>
6   <head>
7   <title>{{ page_title }}</title>
8   <link rel='stylesheet' type='text/css' href='/assets/css/default_1.css' >
9   </head>
10  <body>
11  <h1>{% block title %}{% endblock %}</h1>

**Comment by ericson-cepeda** [comment]
@piousbox, could you please tell me what did cause this issue?

**Comment by piousbox** [comment]
Sorry, I don't think I got it to work the way I wanted. I switched to using other technology. In that project, for ease of use I believe I reverted to writing vanilla Javascript.
