### ISSUE TITLE
django-coffeescript and the staticfiles app

### ISSUE THREAD

**Issue by roalddevries** [andreyfedoseev/django-coffeescript#4]
I've run in another little probleem with (django-coffeescript and) django-less:
- I use the staticfiles app to collect my staticfiles, and have some less-file in custom/static/custom/style.less
- In my development environment, I prefer not to do "collectstatic" all the time, so I use the following code in my urls.py:
  
  if settings.DEBUG:
      urlpatterns += staticfiles_urlpatterns()
      urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
- Now if I use the following code in my templates, django-less can't find the source less file.
  
  {% load less %}
  {% less 'custom/style.less' %}

I think it would be a nice feature if django-less would try to find files in the dirs that staticfiles searches (as a fallback for the STATIC_ROOT directory).

**Comment by andreyfedoseev** [comment]
This is fixed in 0.5.1
