### ISSUE TITLE
work in debug mode

### ISSUE THREAD

**Issue by xenolog** [andreyfedoseev/django-coffeescript#9]
смотри какая петрушка получается. Если ты отлаживаешься локально, например в PyCharm'e и для отдачи статики в urls.py пользуешь примерно вот это:

```
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^{0}(?P<path>.*)$'.format(settings.MEDIA_URL.lstrip('/')), 'django.views.static.serve', {
           'document_root': settings.MEDIA_ROOT,
            }),
    )
```

то джанга сама ищет статику по всех аппах, и уже не смотрит в staticfiles_dirs
в итоге получается, что такой замечательный продукт работает в продакшене и не работает в дебаг режиме :(

выход который видится мне - в дебаг-моде  искать файл аналогично джанге и создавать COFFEESCRIPT_OUTPUT_DIR рядом с файлом скрипта в аппе.

**Comment by andreyfedoseev** [comment]
Fixed in 5d3a6a92bdcbae486bb5a59c3c2a8282c300abcd
